name: "AKS Deployment Pipeline with GitHub Actions"

on:
 push:
 workflow_dispatch:

env:
 TF_LOG: INFO

jobs:
 aks:
   name: "AKS Pipeline"
   runs-on: self-hosted
   defaults:
     run:
       shell: bash
       working-directory: .

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Configure access from root
       id: access
       run: sudo cp -fr /root/.kube $HOME/

     - name: K8s Control Apply
       id: apply
       run: kubectl apply -f pyweb.yml
